language: node_js
sudo: false
node_js:
- '8'
- '10'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
env:
  global:
  - DEBUG='* -superagent -express:* -mocha:* -babel -eslint*'
  - CXX=g++-4.8
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  irc:
    channels:
    - secure: K3cbtuUTxNzKVPTlWd4/LqvzC2NdbTNGKV6+/L30Suk0BbptY781Iy9RyyDglz07DgCRD83OxH47Uxo9zE48KTmL95mkJAiWB+fLSoLILLUgOq/tDtG41hQB5WMrgyoZD0FNLHzqBzdwDm4SQNcez50dLRmY88orCx9ginpYo8XxVhen3DiO136Lgoh50FeN/7wALfKJIIYZX/3h3/YoqLcwzSV0lq1zs7Ej5sF8H+5gnhETw9C0B2jWiZWCOTBBplIbOcfixv/fDXghDDKs6OSKu6n5ylES2QbJ+Wir9hAXTjSMg1vde8gd5//jJkAM2uawYOxFsqGO+LBJqS++z9SU0ccngwayFynHuFwy5lmrEZdA2Sy08sVq63qY5cDdrr+294h6H1fj2o6H5TsSMr7bmMpE5NqkksMRGlSBzoolfBE78REA/YGsJNc4Ir3zWa1ovR8/kMg23QaK57vP0JuLhLNcJYNC/spXAnlem5lzgqI0S21uh2UptuFpH7u16JnjpMM+kNX0WOddiJ73oB88FNHtumjsrhTjcLnZE/Z6zt9ZcYgm8UPgNEwMFLnTlIrrhdn7G1CZMscosM7oclWLRKdrixY/BDvxMMNSpFInLGcdS2JFDFu1iN/fpJFBr2+mcZTTDhZYq4t1D9ks4DY5xH8CH/hYxXp1MZFxSz4=
    on_success: change
    on_failure: always
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    - 'Change view : %{compare_url}'
    - 'Build details : %{build_url}'
    - 'Commit message : %{commit_message}'
deploy:
  provider: npm
  email: taskcluster-accounts@mozilla.com
  skip_cleanup: true
  api_key:
    secure: Y7eKcR01ja1D/XKrdOZbyjjD/pKG3Io7E5JQOA0O5Tseb5AlEGSu4fjVspZe3K/B/I17QhTM0owKsfCaodSWuNe/Z82PNlBN4d7xuO9nZxfDc2dJo+pWv1iquoaBpkrV1n5zAeYnPAcQALn84vECaY3REfzLEzEAaQZu31I5kHE6UtpQqRKhcXC8P/0pAuaV4qalEG52VYQs6TDhpG4SiWBUVASsrZP6ybPB6/vsstMXdIvqUJyh81UIHBLrcoY3g8IQpHRygPiNcgi9Jp2SxHDsAgYpq3gzm2/qiIfLUE8FUMhCMJBq/ehi9BvoMXYPr2Eg4Q6++N4dGEiu0fwXQQ1PaFyGZI0V/1aioHwDta2l7NTmEtSlT8a8KZkkKmnnq+YLkOt2HKGi47tPNJwNZ3/YUrLunGLfQNSUXLf/KqSmkao7gDxFMYNAm/tJCaWvQM7h7dT2Narhvdmm4PzxUG9Ngs3LyplD3VO+jPVl67PIK9XRwQbsiU8/vFW+wcRS98HDLT+DaYKOHc/lMjhnPYKlEdaEE7oKwqHbVXfDhtMV4GOvVyA5knO+9VHZ6hdZ5F+YGuivWOpuyNxkmW9B0qiDrHf7Gy6jMpDORLT/5J/hh1vPYmcKmtmMYiJghE9nfoFC7GI0q87z2ckp12S39lV02vMe2i6gtNNcDLbH6sA=
  on:
    tags: true
    repo: taskcluster/pulse-publisher
