defaults:
  testBucket: "test-bucket-for-any-garbage"
  aws:
    accessKeyId:      "..."
    secretAccessKey:  "..."
  # this client should have pulse:namespace:taskcluster-tests-*
  taskcluster:
    clientId: "..."
    accessToken: "..."
  pulse:
    username: "..."
    password: "..."
